# Generated by Django 3.0.5 on 2020-05-05 02:15

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talentSite.storage_backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=50, null=True)),
                ('lastName', models.CharField(default='', max_length=50, null=True)),
                ('buyerLevel', models.IntegerField(default=0)),
                ('sellerLevel', models.IntegerField(default=0)),
                ('buyerRating', models.IntegerField(default=0)),
                ('sellerRating', models.IntegerField(default=0)),
                ('city', models.CharField(choices=[('AG', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CM', 'Campeche'), ('CS', 'Chiapas'), ('CH', 'Chihuahua'), ('CX', 'CDMX'), ('CO', 'Coahuila'), ('CL', 'Colima'), ('DG', 'Durango'), ('EM', 'Estado de México'), ('GT', 'Guanajuato'), ('GR', 'Guerrero'), ('HG', 'Hidalgo'), ('JC', 'Jalisco'), ('MI', 'Michoacán'), ('MO', 'Morelos'), ('NA', 'Nayarit'), ('NL', 'Nuevo León'), ('OA', 'Oaxaca'), ('PU', 'Puebla'), ('QT', 'Querétaro'), ('QR', 'Quintana Roo'), ('SL', 'San Luis Potosí'), ('SI', 'Sinaloa'), ('SO', 'Sonora'), ('TB', 'Tabasco'), ('TM', 'Tamaulipas'), ('TL', 'Tlaxcala'), ('VE', 'Veracruz'), ('YU', 'Yucatán'), ('ZA', 'Zacatecas')], default='CX', max_length=2)),
                ('profilePic', models.ImageField(null=True, storage=talentSite.storage_backends.PublicMediaStorage(file_overwrite=True), upload_to=apps.profiles.models.UserProfile.generate_filename)),
                ('badges', models.ManyToManyField(blank=True, to='badges.Badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userCategory1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_userprofile_primary_category', to='gigs.Category')),
                ('userCategory2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_userprofile_secondary_category', to='gigs.Category')),
            ],
        ),
    ]
