# Generated by Django 3.0.5 on 2020-05-05 09:24

import apps.profiles.models
from django.db import migrations, models
import talentSite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200505_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coverImage',
            field=models.ImageField(null=True, storage=talentSite.storage_backends.PublicMediaStorage(file_overwrite=True), upload_to=apps.profiles.models.UserProfile.generate_filename_cover),
        ),
    ]
