# Generated by Django 3.0.5 on 2020-05-05 09:29

import apps.profiles.models
from django.db import migrations, models
import talentSite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, storage=talentSite.storage_backends.PublicMediaStorage(file_overwrite=True), upload_to=apps.profiles.models.UserProfile.generate_filename_cover),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, storage=talentSite.storage_backends.PublicMediaStorage(file_overwrite=True), upload_to=apps.profiles.models.UserProfile.generate_filename),
        ),
    ]
