# Generated by Django 3.0.5 on 2020-05-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_auto_20200504_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.Gig')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
            },
        ),
    ]
