# Generated by Django 3.0.5 on 2020-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
