# Generated by Django 3.0.8 on 2020-07-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_auto_20200505_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
