# Generated by Django 3.0.8 on 2020-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_auto_20200717_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='deliveryTime',
            field=models.IntegerField(choices=[(1, ' 1  día'), (2, ' 2  días'), (3, ' 3  días'), (4, ' 4  días'), (5, ' 5  días'), (6, ' 6  días'), (7, ' 7  días'), (8, ' 8  días'), (9, ' 9  días'), (10, ' 10  días'), (11, ' 11  días'), (12, ' 12  días'), (13, ' 13  días'), (14, ' 14  días'), (15, ' 15  días'), (16, ' 16  días'), (17, ' 17  días'), (18, ' 18  días'), (19, ' 19  días'), (20, ' 20  días'), (21, ' 21  días'), (22, ' 22  días'), (23, ' 23  días'), (24, ' 24  días'), (25, ' 25  días'), (26, ' 26  días'), (27, ' 27  días'), (28, ' 28  días')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='revisions',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (100, 'Ilimitadas')]),
        ),
    ]
