# Generated by Django 3.0.8 on 2020-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_auto_20200721_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='isFast',
            field=models.IntegerField(default=False),
        ),
    ]
