# Generated by Django 3.0.8 on 2020-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_auto_20200722_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='description',
            field=models.TextField(),
        ),
    ]
