# Generated by Django 3.0.8 on 2020-07-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_auto_20200722_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='description',
            field=models.TextField(default='aa', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extra',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement',
            field=models.TextField(max_length=50),
        ),
    ]
