# Generated by Django 3.0.8 on 2020-09-22 08:00

import apps.gigs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talentSite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0018_auto_20200918_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrivate', models.BooleanField()),
                ('publicFile', models.FileField(null=True, storage=talentSite.storage_backends.PublicMediaStorage, upload_to=apps.gigs.models.UserFile.generate_filename)),
                ('privateFile', models.FileField(null=True, storage=talentSite.storage_backends.PrivateMediaStorage, upload_to=apps.gigs.models.UserFile.generate_filename)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('fileExtension', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('propietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietary', to=settings.AUTH_USER_MODEL)),
                ('sharedWith', models.ManyToManyField(related_name='sharedWith', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.Order')),
            ],
            options={
                'verbose_name': 'RequirementClient',
                'verbose_name_plural': 'RequirementClients',
            },
        ),
    ]
