# Generated by Django 3.0.8 on 2020-09-22 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0019_requirementclient_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementclient',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requirementclient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirementclient',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requirementclient',
            name='requirement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gigs.Requirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirementclient',
            name='userFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.UserFile'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
