# Generated by Django 3.0.8 on 2020-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0020_auto_20200922_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='images',
        ),
        migrations.AddField(
            model_name='gig',
            name='files',
            field=models.ManyToManyField(to='gigs.UserFile'),
        ),
    ]
