# Generated by Django 3.0.8 on 2020-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0021_auto_20200922_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
