# Generated by Django 3.0.8 on 2020-09-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0024_auto_20200922_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementclient',
            name='order',
        ),
    ]
