# Generated by Django 3.0.8 on 2020-09-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0026_auto_20200922_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementclient',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gigs.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gigs.Order'),
            preserve_default=False,
        ),
    ]
