# Generated by Django 3.0.8 on 2020-09-23 04:15

import apps.gigs.models
from django.db import migrations, models
import talentSite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0027_auto_20200922_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='privateFile',
            field=models.FileField(null=True, storage=talentSite.storage_backends.PrivateMediaStorage(), upload_to=apps.gigs.models.UserFile.generate_filename),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='publicFile',
            field=models.FileField(null=True, storage=talentSite.storage_backends.PublicMediaStorage(), upload_to=apps.gigs.models.UserFile.generate_filename),
        ),
    ]
