# Generated by Django 3.0.8 on 2020-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0028_auto_20200922_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementclient',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
