# Generated by Django 3.0.5 on 2020-05-05 02:15

import apps.badges.models
from django.db import migrations, models
import talentSite.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(storage=talentSite.storage_backends.PublicMediaStorage(), upload_to=apps.badges.models.Badge.upload_to_path)),
                ('description', models.TextField(default='')),
                ('tier', models.IntegerField(default=1)),
            ],
        ),
    ]
