# Generated by Django 3.0.5 on 2020-05-05 02:15

import apps.portfolios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talentSite.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BA', 'Básico'), ('IN', 'Intermedio'), ('AV', 'Avanzado'), ('NB', 'Nativo / Bilingue')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('logo', models.ImageField(null=True, storage=talentSite.storage_backends.StaticStorage(file_overwrite=False), upload_to=apps.portfolios.models.Program.generate_filename)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=600, null=True)),
                ('experience', models.TextField()),
                ('education', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('abilities', models.ManyToManyField(blank=True, to='portfolios.Ability')),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios_portfolio_coverImage', to='gigs.UserImage')),
                ('gallery', models.ManyToManyField(related_name='portfolios_portfolio_gallery', to='gigs.UserImage')),
                ('languages', models.ManyToManyField(blank=True, to='portfolios.Language')),
                ('programs', models.ManyToManyField(blank=True, to='portfolios.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.LanguageLevel'),
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.LanguageName'),
        ),
    ]
