MX_CITY_CHOICES = [
    ('AG', 'Aguascalientes'),
    ('BC', 'Baja California'),
    ('BS', 'Baja California Sur'),
    ('CM', 'Campeche'),
    ('CS', 'Chiapas'),
    ('CH', 'Chihuahua'),
    ('CX', 'CDMX'),
    ('CO', 'Coahuila'),
    ('CL', 'Colima'),
    ('DG', 'Durango'),
    ('EM', 'Estado de México'),
    ('GT', 'Guanajuato'),
    ('GR', 'Guerrero'),
    ('HG', 'Hidalgo'),
    ('JC', 'Jalisco'),
    ('MI', 'Michoacán'),
    ('MO', 'Morelos'),
    ('NA', 'Nayarit'),
    ('NL', 'Nuevo León'),
    ('OA', 'Oaxaca'),
    ('PU', 'Puebla'),
    ('QT', 'Querétaro'),
    ('QR', 'Quintana Roo'),
    ('SL', 'San Luis Potosí'),
    ('SI', 'Sinaloa'),
    ('SO', 'Sonora'),
    ('TB', 'Tabasco'),
    ('TM', 'Tamaulipas'),
    ('TL', 'Tlaxcala'),
    ('VE', 'Veracruz'),
    ('YU', 'Yucatán'),
    ('ZA', 'Zacatecas'),
]
